name: Reusable workflow example

on:
  workflow_call:
    inputs:
      SHA:
        required: true
        type: string
        default: ''
    
jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
    call-existing-workflow:
      - uses: ./.github/workflows/test.yml
        with:
          SHA: ${{ inputs.SHA }}
        