name: Seed Job
on:
  pull_request_review:
    types: [submitted]
    paths:
      - './.github/workflows/*'

permissions: read-all
jobs:
  call-seed-job:
    if: github.event.review.state == 'approved' && github.event.review.body == 'Run seed job'
    uses: ./.github/workflows/seed-job-new-file.yml
    with:
      SHA: '12345'
