name: Seed Job
on:
  workflow_dispatch:
    inputs:
      SHA:
        description: 'GitHub SHA'
        required: true
        default: ''
permissions: read-all
jobs:
  call-seed-job:
    if: ${{ github.event.inputs.SHA }}
    runs-on: ubuntu-latest
    steps: 
      - name: Call updated workflow
        uses: ./.github/workflows/seed-job-new-file.yml
        with:
          SHA: ${{ github.event.inputs.SHA }}
