name: Seed job with comment

on:
  pull_request_review:
    branches: master
    types:
      - "submitted"
    

permissions: read-all

jobs:
  Seed-job:
    if: github.event.review.state == "approved" && startsWith(github.event.review.comment,"seed")
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Checking downloaded repo
      run: ls -a