name: Seed job
on:
  pull_request_target:
    branches: [master]
  workflow_dispatch:
    inputs:
      SHA:
        description: 'GitHub SHA'
        required: true
        default: ''
      # workflow-file-name:
      #   required: true
      #   description: 'Workflow file name (including the yml file type)' 
      #   default: ''
permissions: read-all
jobs:
  Seed-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Echo from Fork
      run: echo from Fork 2!
  call-reusable-seed-job:
    uses: ./.github/workflows/reusable-seed-job.yml
    with:
      SHA: ${{ github.event.inputs.SHA }}
      #workflow-file-name: ${{ github.event.inputs.workflow-file-name }}
      
        