name: Seed job with comment

on:
  workflow_dispatch:
    inputs:
      runSeedJob:
        description: 'Write the name of the file that youd like to run.'
        default: "File"
        required: true 

permissions: read-all



jobs:
  Seed-job:
    runs-on: ubuntu-latest
    env:
      WORKFLOW: ${{github.event.review.body}}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Vars
      run: echo $WORKFLOW    