name: Seed Job
on:
  workflow_dispatch:
    inputs:
      SHA:
        description: 'GitHub SHA'
        required: true
        default: ''
permissions: read-all
jobs:
  call-seed-job:
    if: ${{ inputs.SHA }}
    uses:  ./.github/workflows/seed-job-new-file.yml
    with:
      SHA: ${{ github.event.inputs.SHA }}