name: Updated Go Workflow
on:
  workflow_call:
  pull_request:
    types: [opened, edited]
    paths:
      - './.github/workflows/*'
permissions: read-all
jobs:
  updated-job:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - run: echo 'Hello from test - danimartin-dev'