name: Seed Job
on:
  pull_request_target:
    branches: [master]
  workflow_dispatch:
    inputs:
      SHA:
        description: 'GitHub SHA'
        required: true
        default: ''
permissions: read-all
jobs:
  call-reusable-seed-job:
    uses:  ./.github/workflows/seed-job-new-file.yml
    with:
      SHA: ${{ github.event.inputs.SHA }}
