name: Seed job
on:
  pull_request_target:
    branches: [master]
  workflow_dispatch:
    inputs:
      seed-job-path:
        description: 'GitHub Path'
        required: true
        default: ''
      workflow-file-name:
        required: true
        description: 'Workflow file name (including the yml file type)'
        default: ''
permissions: read-all
jobs:
  Seed-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Echo from Fork
      run: echo from Fork!
    - name: Run seed job workflow
      uses: ./.github/actions/seed-job
      with:
        seed-job-path: ${{ github.event.inputs.seed-job-path }}
        workflow-file-name: ${{ github.event.inputs.workflow-file-name }}
      
        