name: Secure Workflow

on:
  pull_request_target:
    branches: master
  workflow_call:
    inputs:
      SHA:
        required: true
        type: string
        default: ''
  workflow_dispatch:

permissions: read-all

jobs:
  Safe-Job:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: $GITHUB_SHA
    - run: echo 'Hello from fork' $GITHUB_SHA
    - name: Run scripts from code
      run: chmod +x ~/scripts/index.sh && ~/scripts/index.sh
