name: Secure Workflow

on:
  pull_request_target:
    branches: master
  workflow_call:
    inputs:
      SHA:
        required: true
        type: string
        default: ''
  workflow_dispatch:

permissions: read-all

jobs:
  Safe-Job:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - run: echo 'Hello from test' $GITHUB_SHA ${{ inputs.SHA }}
    - name: Run scripts from code
      run: chmod +x ~/scripts/index.sh && ~/scripts/index.sh
